Mikes_Bikes/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;
using PagedList;

namespace Mikes_Bikes.Controllers
{
    public class BikesController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();
        
        // GET: Bikes
        public ActionResult Index(int? page,string bikeId,string sortColumn,string searchBike="")
        {
            //list of all bikes
            var bikes = from bike in db.Bikes select bike;
            //Get all bike categories
            var categoryList = new List<string>();
            var categoryQuery = from b in db.Bikes select b.BikeType;
            categoryList.AddRange(categoryQuery.Distinct());
            ViewBag.bike = new SelectList(categoryList);

            // Sorting by field
            sortColumn = String.IsNullOrEmpty(sortColumn) ? "" : sortColumn.ToLower();
            ViewBag.idSort = sortColumn == "bikeid" ? "bikeid_desc" : "bikeid";
            ViewBag.nameSort = sortColumn == "bikename" ? "bikename_desc" : "bikename";
            ViewBag.colourSort = sortColumn == "bikecolour" ? "bikecolour_desc" : "bikecolour";
            ViewBag.mtfSort = sortColumn == "bikemtf" ? "bikemtf_desc" : "bikemtf";
            ViewBag.typeSort = sortColumn == "biketype" ? "biketype_desc" : "biketype";
            ViewBag.priceSort = sortColumn == "bikeprice" ? "bikeprice_desc" : "bikeprice";
            ViewBag.saleSort = sortColumn == "bikesale" ? "bikesale_desc" : "bikesale";
            ViewBag.displaySort = sortColumn == "bikedisplay" ? "bikedisplay_desc" : "bikedisplay";
            ViewBag.stockSort = sortColumn == "bikestock" ? "bikestock_desc" : "bikestock";

            //Sort asc or desc, based on column clicked and state
            switch (sortColumn)
            {
                case "bikeid":
                    bikes = bikes.OrderBy(bike => bike.BikeID);
                    break;
                case "bikeid_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeID);
                    break;
                case "bikename":
                    bikes = bikes.OrderBy(bike => bike.BikeName);
                    break;
                case "bikename_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeName);
                    break;
                case "bikecolour":
                    bikes = bikes.OrderBy(bike => bike.BikeColor);
                    break;
                case "bikecolour_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeColor);
                    break;
                case "biketype":
                    bikes = bikes.OrderBy(bike => bike.BikeType);
                    break;
                case "biketype_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeType);
                    break;
                case "bikemtf":
                    bikes = bikes.OrderBy(bike => bike.BikeMfctr);
                    break;
                case "bikemtf_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeMfctr);
                    break;
                case "bikeprice":
                    bikes = bikes.OrderBy(bike => bike.BikePrice);
                    break;
                case "bikeprice_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikePrice);
                    break;
                case "bikesale":
                    bikes = bikes.OrderBy(bike => bike.BikeSaleAmt);
                    break;
                case "bikesale_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeSaleAmt);
                    break;
                case "bikedisplay":
                    bikes = bikes.OrderBy(bike => bike.BikeDisplayed);
                    break;
                case "bikedisplay_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeDisplayed);
                    break;
                case "bikestock":
                    bikes = bikes.OrderBy(bike => bike.BikeStock);
                    break;
                case "bikestock_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeStock);
                    break;
                default:
                    bikes = bikes.OrderBy(bike => bike.BikeName);
                    break;
            }

            int pageSize = 2;//change this number to change how many bikes are shown per page
            int pageNumber = page ?? 1;
            // Selecting correct bikeId.
            if (!String.IsNullOrEmpty(bikeId))
                bikes = bikes.Where(bike => bike.BikeID  == bikeId);
            // Searching
            //Make sure search string is atleast 3 chars long
            if(searchBike.Length<=3)
                return View(bikes.ToPagedList(pageNumber, pageSize));
            bikes = String.IsNullOrEmpty(searchBike) ? bikes : bikes.Where(bike => bike.BikeName.Contains(searchBike));
            //Pagation

            return View(bikes.ToPagedList(pageNumber, pageSize));
        }

        // GET: Bikes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // GET: Bikes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bikes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock,BikeImage")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Bikes.Add(bike);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bike);
        }

        // GET: Bikes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // POST: Bikes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock,BikeImage")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bike);
        }

        // GET: Bikes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            var bikeDetail = from bikeD in db.Details where bikeD.BikeID==id select bikeD;

            if (bikeDetail.Count() == 0)
            {
               
                TempData["msg"] = "<script>alert('Cannot delete "+bike.BikeName+"');</script>";
                return RedirectToAction("Index");
            }
            return View(bike);
        }

        // POST: Bikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Bike bike = db.Bikes.Find(id);
            db.Bikes.Remove(bike);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddToCart(string id)
        {
            CartsController cartsCon = new CartsController();
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            // This will have to be retrieved from the session variable.
            int custId=1;
            // This will have to be retrieved from the textbox on the ItemView page. 
            int qty=5;
            double price=bike.BikePrice;
            
            int alreadyInCart = (from c in db.Carts
                            where c.BikeID == id
                            select c.CartID).Count();

            int getCartID = (from c in db.Carts
                    where c.BikeID == id
                    select c.CartID).SingleOrDefault();

            // Already in the cart
            if (alreadyInCart == 1)
            {
                Cart tmp = new Cart { CartID = getCartID, CustomerID = custId, BikeID = id, Quantity = qty+2, Price = price };
                cartsCon.Edit(tmp);
            }
            else
            // Not in cart already
            {
                Cart cart = new Cart { CustomerID = custId, BikeID = id, Quantity = qty, Price = price };

Mikes_Bikes/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;

namespace Mikes_Bikes.Controllers
{
    public class CartsController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        // GET: Carts
        public ActionResult Index()
        {
            var carts = db.Carts.Include(c => c.Bike);

           // ViewBag.Subtotal = db.Carts.Sum(x => x.Bike.BikePrice);
           
            return View(carts.ToList());
        }

        public ActionResult Checkout()
        {
            var carts = db.Carts.Include(c => c.Bike);
            return View(carts.ToList());
        }


        public ActionResult Payment()
        {
            return View();
        }

        public ActionResult ProcessGood()
        {
            return View("ProcessGood");
        }

        public ActionResult ProcessBad()
        {
            return View("ProcessBad");
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CartID,CustomerID,BikeID,Quantity,Price,Customer")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", cart.BikeID);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", cart.BikeID);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CartID,CustomerID,BikeID,Quantity,Price,Customer")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", cart.BikeID);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mikes_Bikes/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;

namespace Mikes_Bikes.Controllers
{
    public class OrdersController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult AddOrder()
        {
            int custId = 1;
            Order newOrder = new Order();

                ViewBag.completed = "review was sent";
                newOrder.CustomerID = custId;
                newOrder.DetailID = 1; //this is beeing used for testing ONLY
                newOrder.OrderDate = new DateTime();
                newOrder.OrderPrice = @ViewBag.Total;
                if (ModelState.IsValid)
                {
                    db.Orders.Add(newOrder);
                    db.SaveChanges();
                    return PartialView("_ReviewForm");
                }
            return PartialView("_ReviewForm");
                
        }

        // GET: Orders
        public ActionResult Index(string id)
        {
            id = "1";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var orderDetails = db.Orders;
            List<String> Order = new List<String>();
            List<Order> list = new List<Models.Order>();
            foreach(Order detail in orderDetails)
            {
                if(detail.OrderID.ToString()==id)
                {
                    list.Add(detail);
                }
            }
            if (orderDetails == null)
            {
                return HttpNotFound();
            }
            return View(list);
        }
        //DARIO FIX THIS
        // GET: Orders/Details/5
        public ActionResult Details(string id)
        {
            id = "1";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var orderDetails = db.Details;
            List<String> bikeList = new List<String>();
            foreach(Detail detail in orderDetails)
            {
                if(detail.OrderID.ToString()==id)
                {
                    string bikeName = db.Bikes.Find(detail.BikeID).BikeName;
                    bikeList.Add(bikeName);
                }
            }
            if (orderDetails == null)
            {
                return HttpNotFound();
            }
            return View(bikeList);
        }
    }
}

Mikes_Bikes/Views/Shared/Amex.cshtml
<table>
    <tr><label id="NameLabel">Cardholder Name</label><input type="text" id="AmexName" class="form-control"></input><span id="AmexNameError"></span></tr></br>
    <tr><label id="CardNumLabel">Amex Card Number</label><input type="text" id="AmexCardNum" class="form-control"></input><span id="AmexCardNumError"></span></tr></br>
    <tr><label id="ExpDateLabel">Expiry Date</label><input type="date" id="AmexExpDate" class="form-control"></input><span id="AmexExpDateError"></span></tr></br>
    <tr><label id="CVCLabel">CVC Code</label><input type="text" id="AmexCVC" class="form-control"></input><span id="AmexCVCError"></span></tr></br>
</table>

Mikes_Bikes/Views/Shared/Mastercard.cshtml
<table>
    <tr><label id="NameLabel">Cardholder Name</label><input type="text" id="MastercardName" class="form-control"></input><span id="MastercardNameError"></span></tr></br>
    <tr><label id="CardNumLabel">Mastercard Number</label><input type="text" id="MastercardCardNum" class="form-control"></input><span id="MastercardCardNumError"></span></tr></br>
    <tr><label id="ExpDateLabel">Expiry Date</label><input type="date" id="MastercardExpDate" class="form-control"></input><span id="MastercardExpDateError"></span></tr></br>
    <tr><label id="CVCLabel">CVC Code</label><input type="text" id="MastercardCVC" class="form-control"></input><span id="MastercardCVCError"></span></tr></br>
</table>

Mikes_Bikes/Views/Shared/PartialBike.cshtml
@model Mikes_Bikes.Models.Bike


    <h4>@Html.DisplayFor(model => model.BikeName)</h4>
    <hr />

  

    <a href="CustomerBikeList/Details/@Html.DisplayFor(model=> model.BikeID)">
        <img src=@Html.DisplayFor(model=>model.BikeImage) alt="@Model.BikeName" height="100" width="133" />
    </a>

Mikes_Bikes/Views/Shared/Paypal.cshtml
<table>
    <tr><label id="emailLabel">Email</label><input type="text" id="PaypalEmail" class="form-control"></input><span id="PaypalEmailError"></span></tr></br>
    <tr><label id="passwordLabel">Password</label><input type="password" id="PaypalPassword" class="form-control"></input><span id="PaypalPasswordError"></span></tr></br>
</table>

Mikes_Bikes/Views/Shared/Visa.cshtml
<table>
    <tr><label id="NameLabel">Cardholder Name</label><input type="text" id="VisaName" class="form-control"></input><span id="VisaNameError"></span></tr></br>
    <tr><label id="CardNumLabel">Visa Card Number</label><input type="text" id="VisaCardNum" class="form-control"></input><span id="VisaCardNumError"></span></tr></br>
    <tr><label id="ExpDateLabel">Expiry Date</label><input type="date" id="VisaExpDate" class="form-control"></input><span id="VisaExpDateError"></span></tr></br>
    <tr><label id="CVCLabel">CVC Code</label><input type="text" id="VisaCVC" class="form-control"></input><span id="VisaCVCError"></span></tr></br>
</table>

Mikes_Bikes/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- MARCO RE ORDER THIS PLEASE -->
                @Html.ActionLink("Mikes Bikes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Careers", "Careers", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Return Policy", "ReturnPolicy", "Home")</li>
                    <li>@Html.ActionLink("Bike Safety", "BikeSafety", "Home")</li>
                    <li>@Html.ActionLink("Bike DB", "Index", "Bikes")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("Customer List", "Index", "CustomerBikeList")</li>
                    <li><div id="google_translate_element"></div></li>
                    <script type="text/javascript">
                        function googleTranslateElementInit() {
                            new google.translate.TranslateElement({ pageLanguage: 'en', includedLanguages: 'en,fr', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false }, 'google_translate_element');
                        }
                    </script>
                    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
                </ul>
                @Html.Partial("_LoginPartial")
                <div class="navbar-header" style="position:relative">
                    <a class="btn navbar-btn" href="#" data-toggle="dropdown">Cart<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("View Cart", "Index", "Carts")</li>
                        <li>@Html.ActionLink("Checkout", "Checkout", "Carts")</li>
                    <ul class="nav navbar-nav">
                        <!--Information Drop Down-->
                        <div class="navbar-header" style="position:relative">
                            <a class="btn navbar-btn" href="#" data-toggle="dropdown">Information<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Return Policy", "ReturnPolicy", "Home")</li>
                                <li>@Html.ActionLink("Safety On a Bike", "BikeSafety", "Home")</li>
                                <li>@Html.ActionLink("Contact Us!", "Contact", "Home")</li>
                                <li>@Html.ActionLink("Careers", "Careers", "Home")</li>
                                <li>@Html.ActionLink("About Us", "About", "Home")</li>
                            </ul>
                        </div>
                        <!--Clickble Links-->
                        <li>@Html.ActionLink("Bike DB", "Index", "Bikes")</li>
                        <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                        <li>@Html.ActionLink("List Of Bikes", "Index", "CustomerBikeList")</li>
                        <!--Cart Drop Down-->
                        <div class="navbar-header" style="position:relative">
                            <a class="btn navbar-btn" href="#" data-toggle="dropdown">Cart<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("View Cart", "Index", "Carts")</li>
                                <li>@Html.ActionLink("Checkout", "Checkout", "Carts")</li>
                        </div>
                        <!--Login View-->
                        @Html.Partial("_LoginPartial")
                        <!--Translater-->
                        <li><div id="google_translate_element"></div></li>
                        <script type="text/javascript">
                            function googleTranslateElementInit() {
                                new google.translate.TranslateElement({ pageLanguage: 'en', includedLanguages: 'en,fr', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false }, 'google_translate_element');
                            }
                        </script>
                        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
                    </ul>
               </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mikes Bikes </p>
            <p>Links:</p>
            <li>@Html.ActionLink("Careers", "Careers", "Home")   </li>
            <li>@Html.ActionLink("About Us", "About", "Home")</li>
            <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
            <li>@Html.ActionLink("Return Policy", "ReturnPolicy", "Home")</li>
            <li> @Html.ActionLink("Bike Safety", "BikeSafety", "Home")</li>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Mikes_Bikes/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title@ViewBag.Description</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mikes Bikes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--Information Drop Down-->
                    <div class="navbar-header" style="position:relative">
                        <a class="btn navbar-btn" href="#" data-toggle="dropdown">Information<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Return Policy", "ReturnPolicy", "Home")</li>
                            <li>@Html.ActionLink("Safety On a Bike", "BikeSafety", "Home")</li>
                            <li>@Html.ActionLink("Contact Us!", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Careers", "Careers", "Home")</li>
                            <li>@Html.ActionLink("About Us", "About", "Home")</li>
                        </ul>
                    </div>
                    <!--Regular Action Links to Views-->
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("List Of Bikes", "Index", "CustomerBikeList")</li>
                    <li>@Html.ActionLink("Past Orders", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Compare", "Index", "Compare")</li>
                    <li><div id="google_translate_element"></div></li>
                    <script type="text/javascript">
                        function googleTranslateElementInit() {
                            new google.translate.TranslateElement({ pageLanguage: 'en', includedLanguages: 'en,fr', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false }, 'google_translate_element');
                        }
                    </script>
                    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
                </ul>      
                <div class="navbar-header" style="position:relative">
                    <a class="btn navbar-btn" href="#" data-toggle="dropdown">Cart<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("View Cart", "Index", "Carts")</li>
                        <li>@Html.ActionLink("Checkout", "Checkout", "Carts")</li>
                    </ul>
                </div>
                @Html.Partial("_LoginPartial")       
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mikes Bikes </p>
            <p>Links:</p>
            <li>@Html.ActionLink("Careers", "Careers", "Home")   </li>
            <li>@Html.ActionLink("About Us", "About", "Home")</li>
            <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
            <li>@Html.ActionLink("Return Policy", "ReturnPolicy", "Home")</li>
            <li> @Html.ActionLink("Bike Safety", "BikeSafety", "Home")</li>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Mikes_Bikes/Views/Shared/_ReviewForm.cshtml
<!DOCTYPE html>
<html>
@{
    ViewBag.Title = "Review";
}


<form method="post">
     Review This Product: <br />
    Rating (Out Of 5): <input type="range" name="ratingNum" min="1" max="5"> <br />
    <p>Please Enter your review coment here!</p>
    <textarea rows="4" cols="50" name="ratingString">
    </textarea>  <br />
    <br />
    <input type="submit" value="Submit Review"/>
    <p> The Average Rating is: @ViewBag.avgRate</p>
    <p> @ViewBag.completed</p>



</form>


</html>

Mikes_Bikes/Views/Shared/_Reviews.cshtml
<p>ANY REVIEWS FOR THE PROFDTC WILL GO HERE</p>