Mikes_Bikes/Models/Detail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Mikes_Bikes.Models
{
    public class Detail
    {
        public int DetailID { get; set; }
        public int OrderID { get; set; }
        public string BikeID { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }

        public virtual Bike Bike { get; set; }
    }

}

Mikes_Bikes/Controllers/CustomerBikeListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;
using PagedList;

namespace Mikes_Bikes.Controllers
{
    public class CustomerBikeListController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        [ChildActionOnly]
        public PartialViewResult Review(string BikeID)
        {
            //get the rating from the databse
            //calcualte the average
            if (db.Ratings.Where(x => x.BikeID == BikeID).Select(x => x.Rate).Count() > 0) //has there been any reviews 
                ViewBag.avgRate = db.Ratings.Where(x => x.BikeID == BikeID).Select(x => x.Rate).Average();
            else
                ViewBag.avgRate = "Sorry no reviews yet";
            return PartialView("_ReviewForm");
         }


        // POST: Bikes/add Review
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Review(string BikeID, int ratingNum, string ratingString)
        {
            int custid = 1;
            Rating newRating = new Rating();
            /*if (ModelState.IsValid)
            {
               db.SaveChanges();
                return PartialView("_ReviewForm");
            }*/
            //the rating strng can not be empty
            if (string.IsNullOrWhiteSpace(ratingString))
            {
                ViewBag.completed = "sorry review can not be blank";
            }
            else
            {

                ViewBag.completed = "review was sent";
                newRating.BikeID = BikeID;
                newRating.CustomerID = custid; //this is beeingn used for testing ONLY
                newRating.Rate = ratingNum;
                newRating.Review = ratingString;
                if (ModelState.IsValid)
                {
                    db.Ratings.Add(newRating);
                    db.SaveChanges();
                    return PartialView("_ReviewForm");
                }

            }
            //we need to recalculate the new average rating
            //get the rating from the databse
            //calcualte the average
            Double averageRating = db.Ratings.Where(x => x.BikeID == BikeID) .Select(x => x.Rate).Average();
            ViewBag.avgRate = averageRating;

            return PartialView("_ReviewForm");
        }

        // GET: Bikes
        public ActionResult Index(int? page, string bikeCat, string sortColumn, string searchBike = "")
        {
            //list of all bikes
            var bikes = from bike in db.Bikes where bike.BikeDisplayed == true select bike;
            //Get all bike categories
            var categoryList = new List<string>();
            var categoryQuery = from b in db.Bikes select b.BikeType;
            categoryList.AddRange(categoryQuery.Distinct());
            ViewBag.bikeCat = new SelectList(categoryList);

            // Sorting by field
            sortColumn = String.IsNullOrEmpty(sortColumn) ? "" : sortColumn.ToLower();
            ViewBag.idSort = sortColumn == "bikeid" ? "bikeid_desc" : "bikeid";
            ViewBag.nameSort = sortColumn == "bikename" ? "bikename_desc" : "bikename";
            ViewBag.colourSort = sortColumn == "bikecolour" ? "bikecolour_desc" : "bikecolour";
            ViewBag.mtfSort = sortColumn == "bikemtf" ? "bikemtf_desc" : "bikemtf";
            ViewBag.typeSort = sortColumn == "biketype" ? "biketype_desc" : "biketype";
            ViewBag.priceSort = sortColumn == "bikeprice" ? "bikeprice_desc" : "bikeprice";
            ViewBag.saleSort = sortColumn == "bikesale" ? "bikesale_desc" : "bikesale";
            ViewBag.displaySort = sortColumn == "bikedisplay" ? "bikedisplay_desc" : "bikedisplay";
            ViewBag.stockSort = sortColumn == "bikestock" ? "bikestock_desc" : "bikestock";

            //Sort asc or desc, based on column clicked and state
            switch (sortColumn)
            {
                case "bikeid":
                    bikes = bikes.OrderBy(bike => bike.BikeID);
                    break;
                case "bikeid_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeID);
                    break;
                case "bikename":
                    bikes = bikes.OrderBy(bike => bike.BikeName);
                    break;
                case "bikename_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeName);
                    break;
                case "bikecolour":
                    bikes = bikes.OrderBy(bike => bike.BikeColor);
                    break;
                case "bikecolour_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeColor);
                    break;
                case "biketype":
                    bikes = bikes.OrderBy(bike => bike.BikeType);
                    break;
                case "biketype_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeType);
                    break;
                case "bikemtf":
                    bikes = bikes.OrderBy(bike => bike.BikeMfctr);
                    break;
                case "bikemtf_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeMfctr);
                    break;
                case "bikeprice":
                    bikes = bikes.OrderBy(bike => bike.BikePrice);
                    break;
                case "bikeprice_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikePrice);
                    break;
                case "bikesale":
                    bikes = bikes.OrderBy(bike => bike.BikeSaleAmt);
                    break;
                case "bikesale_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeSaleAmt);
                    break;
                case "bikedisplay":
                    bikes = bikes.OrderBy(bike => bike.BikeDisplayed);
                    break;
                case "bikedisplay_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeDisplayed);
                    break;
                case "bikestock":
                    bikes = bikes.OrderBy(bike => bike.BikeStock);
                    break;
                case "bikestock_desc":
                    bikes = bikes.OrderByDescending(bike => bike.BikeStock);
                    break;
                default:
                    bikes = bikes.OrderBy(bike => bike.BikeName);
                    break;
            }

            int pageSize = 2;//change this number to change how many bikes are shown per page
            int pageNumber = page ?? 1;
            // Selecting correct bikeId.
            if (!String.IsNullOrEmpty(bikeCat))
                bikes = bikes.Where(bike => bike.BikeType == bikeCat);
            // Searching
            //Make sure search string is atleast 3 chars long
            if (searchBike.Length <= 3)
                return View(bikes.ToPagedList(pageNumber, pageSize));
            bikes = String.IsNullOrEmpty(searchBike) ? bikes : bikes.Where(bike => bike.BikeName.Contains(searchBike));
            //Pagation

            return View(bikes.ToPagedList(pageNumber, pageSize));
        }

        // GET: Bikes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // GET: Bikes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bikes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Bikes.Add(bike);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bike);
        }

        // GET: Bikes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // POST: Bikes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bike);
        }

        // GET: Bikes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

Mikes_Bikes/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;

namespace Mikes_Bikes.Controllers
{
    public class DetailsController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        // GET: Details
        public ActionResult Index()
        {
            var details = db.Details.Include(d => d.Bike);
            return View(details.ToList());
        }

        // GET: Details/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // GET: Details/Create
        public ActionResult Create()
        {
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName");
            return View();
        }

        // POST: Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DetailID,OrderID,BikeID,Price,Quantity")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Details.Add(detail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // GET: Details/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // POST: Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DetailID,OrderID,BikeID,Price,Quantity")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // GET: Details/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // POST: Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Detail detail = db.Details.Find(id);
            db.Details.Remove(detail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mikes_Bikes/Views/CustomerBikeList/Create.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BikeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeColor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeColor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeMfctr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeMfctr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeMfctr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescFR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescFR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescFR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeSaleAmt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeSaleAmt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeSaleAmt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BikeDisplayed)
                    @Html.ValidationMessageFor(model => model.BikeDisplayed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mikes_Bikes/Views/CustomerBikeList/Delete.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BikeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeColor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeMfctr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescFR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeSaleAmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeStock)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mikes_Bikes/Views/CustomerBikeList/Details.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = @Model.BikeName;
    ViewBag.Description =","+@Model.BikeDescEN;

}

<h2>Details</h2>

<div>
    <h4>Bike</h4>
    <hr />
    <img src=@Html.DisplayFor(model=>model.BikeImage) alt="@Model.BikeName" height="100" width="133" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BikeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeColor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeMfctr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescFR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeSaleAmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeStock)
        </dd>

    </dl>
</div>
<p>  
    <!-- To change maybe: quantity -->
    @Html.ActionLink("Add To Cart", "AddToCart", new { id = @Html.DisplayFor(model => model.BikeID) , q=1})
    @Html.ActionLink("Back to List", "Index","CustomerBikelist")
</p>

<p>



    @Html.Action("Review", "CustomerBikelist", new { BikeID = Model.BikeID })

</p>

Mikes_Bikes/Views/CustomerBikeList/Index.cshtml
 
@model PagedList.IPagedList<Mikes_Bikes.Models.Bike>
@using PagedList.Mvc;



@{
    ViewBag.Title = "Our Bikes";
    ViewBag.Description = ",Search Through Our Entire Inventory Of Great Bikes";

}
<style>
    .floatLeft {
        width: 10%;
        float: left;
    }

    .floatRight {
        width: 90%;
        float: right;
    }

    .container {
        overflow: hidden;
    }
</style>

<h2>Index</h2>
@using (Html.BeginForm("Index", "CustomerBikeList", FormMethod.Get))
{
    <p>
        <!-- Html.DropDownList(keyInViewBag&variableName, nameForEmptyString) -->
        Catergory : @Html.DropDownList("bikeCat", "All")<br />
        Search : @Html.TextBox("searchBike")<br />
        <input type="submit" value="Search" />
    </p>
}
<div class="container">
    <div class="floatLeft">
        <table class="table">

            <tr>
                <td>@Html.ActionLink("Bike Name", "Index", new { sortColumn = ViewBag.nameSort })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Bike Colour", "Index", new { sortColumn = ViewBag.colourSort })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Bike Manufacture", "Index", new { sortColumn = ViewBag.mtfSort })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Bike Type", "Index", new { sortColumn = ViewBag.typeSort })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Bike Price", "Index", new { sortColumn = ViewBag.priceSort })</td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Bike Sale", "Index", new { sortColumn = ViewBag.saleSort })
                </td>
            </tr>
        </table>
    </div>
    <div class=" floatRight">
       <table>
        @foreach (var item in Model)
        {
            <tr>
                <td colspan="6">
                    @Html.Partial("PartialBike", item) 
                </td>
            </tr>
            <tr>
                <td>
                    
                    @{ 
                        if(item.BikeSaleAmt<1)
                        {
                            double saleAmt = ((double)item.BikePrice * (double)item.BikeSaleAmt);
                            double salePrice = (double)item.BikePrice - saleAmt;
                            @Html.Raw("<del>$" + item.BikePrice+"</del> $"+salePrice.ToString());
                        }
                        else
                        {
                            @Html.Raw("$");
                           @Html.DisplayFor(model => item.BikePrice);
                        }
                    }
                    
                </td>
            </tr>
        }
        </table>
    </div>
</div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))