Mikes_Bikes/Models/Detail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Mikes_Bikes.Models
{
    public class Detail
    {
        public int DetailID { get; set; }
        public int OrderID { get; set; }
        public string BikeID { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }

        public virtual Bike Bike { get; set; }
    }

}

Mikes_Bikes/Controllers/CompareController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;

namespace Mikes_Bikes.Controllers
{
    public class CompareController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        // GET: Compare
        public ActionResult Index(string compare1 = "", string compare2 = "")
        {
            var bikes = from bike in db.Bikes select bike;

            bikes = String.IsNullOrEmpty(compare1) ? bikes : bikes.Where(bike => bike.BikeName == compare1 || bike.BikeName == compare2 );

            return View(bikes.ToList());
        }

        // GET: Compare/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // GET: Compare/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Compare/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock,BikeImage")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Bikes.Add(bike);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bike);
        }

        // GET: Compare/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // POST: Compare/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BikeID,BikeName,BikeColor,BikeMfctr,BikeType,BikePrice,BikeDescEN,BikeDescFR,BikeSaleAmt,BikeDisplayed,BikeStock,BikeImage")] Bike bike)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bike);
        }

        // GET: Compare/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bike bike = db.Bikes.Find(id);
            if (bike == null)
            {
                return HttpNotFound();
            }
            return View(bike);
        }

        // POST: Compare/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Bike bike = db.Bikes.Find(id);
            db.Bikes.Remove(bike);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mikes_Bikes/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mikes_Bikes.Models;

namespace Mikes_Bikes.Controllers
{
    public class DetailsController : Controller
    {
        private Mikes_BikesContext db = new Mikes_BikesContext();

        // GET: Details
        public ActionResult Index()
        {
            var details = db.Details.Include(d => d.Bike);
            return View(details.ToList());
        }

        // GET: Details/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // GET: Details/Create
        public ActionResult Create()
        {
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName");
            return View();
        }

        // POST: Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DetailID,OrderID,BikeID,Price,Quantity")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Details.Add(detail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // GET: Details/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // POST: Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DetailID,OrderID,BikeID,Price,Quantity")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BikeID = new SelectList(db.Bikes, "BikeID", "BikeName", detail.BikeID);
            return View(detail);
        }

        // GET: Details/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // POST: Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Detail detail = db.Details.Find(id);
            db.Details.Remove(detail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mikes_Bikes/Views/Compare/CompareView.cshtml
@model IEnumerable<Mikes_Bikes.Models.Bike>

@{
    ViewBag.Title = "CompareView";
}

<br />
<br />
<h2>Comparing Bikes</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BikeID)        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BikeID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeMfctr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDescEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDescFR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeSaleAmt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDisplayed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeStock)
            </td>
        </tr>
    }

</table>

Mikes_Bikes/Views/Compare/Create.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BikeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeColor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeColor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeMfctr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeMfctr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeMfctr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescFR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescFR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescFR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeSaleAmt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeSaleAmt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeSaleAmt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BikeDisplayed)
                    @Html.ValidationMessageFor(model => model.BikeDisplayed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mikes_Bikes/Views/Compare/Delete.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BikeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeColor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeMfctr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescFR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeSaleAmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeStock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mikes_Bikes/Views/Compare/Details.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BikeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeColor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeMfctr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDescFR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeSaleAmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeDisplayed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeStock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BikeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mikes_Bikes/Views/Compare/Edit.cshtml
@model Mikes_Bikes.Models.Bike

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BikeID)

        <div class="form-group">
            @Html.LabelFor(model => model.BikeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeColor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeColor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeMfctr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeMfctr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeMfctr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDescFR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeDescFR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeDescFR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeSaleAmt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeSaleAmt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeSaleAmt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeDisplayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BikeDisplayed)
                    @Html.ValidationMessageFor(model => model.BikeDisplayed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mikes_Bikes/Views/Compare/Index.cshtml
@model IEnumerable<Mikes_Bikes.Models.Bike>

@{
    ViewBag.Title = "Index";
}

<br />
<br />
<h2>Choose Bikes to Compare</h2>

@using (Html.BeginForm("Index", "Compare", FormMethod.Get))
{
    <table class="table1">
        <tr>
            <th>
                Compare
            </th>
            <th></th>
        </tr>

        <tr>
            <td>
                <input type="text" id="compare1" name="compare1" placeholder="First Compare Item" />
            </td>
            <td>
                <input type="text" id="compare2" name="compare2" placeholder="First Compare Item" />
            </td>
        </tr>

    </table>

    <input type="submit" value="Compare" id="SubmitCompare" />
}
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BikeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeMfctr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDescEN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDescFR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeSaleAmt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDisplayed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <!----------- This is here TEMPORARILY ----------->
            <td>
                @Html.DisplayFor(model => item.BikeID)
            </td>
            <!------------------------------------------------>
            <td>
                @Html.DisplayFor(modelItem => item.BikeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeMfctr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDescEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDescFR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeSaleAmt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeDisplayed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BikeStock)
            </td>
        </tr>
    }
</table>